### ISSUE TITLE
lockless radix tree

### ISSUE THREAD

**Issue by yuyang0** [antirez/rax#9]
Is it possible to convert this radix tree implementation to a lockless radix tree(such as using with RCU)?

**Comment by antirez** [comment]
Technically yes, but probably a lot of work is needed: Rax stores pointers at unaligned addresses which may cause portability problems with atomic primitives in certain contexts, and most critical sections of the code should be rewritten in order to perform operations in a lock free manner. So should be possible and probably it is simpler to start from Rax than from scratch, but is a non trivial project.
